#!/usr/local/bin/zsh

# Set the ADVENT_SESSION from the session id in your logged in browser in your env variables
# Set the ADVENT_USER_AGENT to something like <your_username> by curl in your env variables
#echo $ADVENT_SESSION
if [ -z "$1" ]
then
    echo "Enter a day number between 1 and 25"
    read -r day
else
    day=$1
fi
url=https://adventofcode.com/2022/day/$day/input
echo "Fetching AoC data for day" "$day"
# echo "from" "$url"
dayResourceFolder=src/main/resources/$day
mkdir "$dayResourceFolder"
cd "$dayResourceFolder" || exit
pwd
touch Day_test.txt
curl -fsSL -A "$ADVENT_USER_AGENT" --cookie session="$ADVENT_SESSION" "$url"  > Day.txt
ls -l